{{-- SPDX-License-Identifier: MIT --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Report Card - {{ $user->name }}</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; color: #1E293B; }
        .header { text-align: center; margin-bottom: 24px; }
        .header h1 { font-size: 20px; margin: 0; color: #0F172A; }
        .header p { margin: 4px 0 0; color: #64748B; font-size: 13px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { background: #1E6FD9; color: white; padding: 8px 12px; text-align: left; font-size: 11px; text-transform: uppercase; }
        td { padding: 8px 12px; border-bottom: 1px solid #E2E8F0; }
        .score { font-weight: 700; }
        .pass { color: #22C55E; }
        .fail { color: #DC2626; }
        .footer { text-align: center; margin-top: 32px; font-size: 11px; color: #94A3B8; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Academic Record</h1>
        <p>{{ $user->name }} · {{ $user->email }}</p>
    </div>

    @if($marks->isEmpty())
        <p style="text-align: center; color: #94A3B8; margin-top: 48px;">No academic records available.</p>
    @else
        <table>
            <thead>
                <tr>
                    <th>Subject</th>
                    <th>Exam</th>
                    <th>Score</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                @foreach($marks as $mark)
                    <tr>
                        <td>{{ $mark->subject->name ?? '—' }}</td>
                        <td>{{ $mark->exam->name ?? '—' }}</td>
                        <td class="score {{ ($mark->marks ?? 0) >= 50 ? 'pass' : 'fail' }}">{{ $mark->marks ?? 0 }}</td>
                        <td>{{ $mark->grade ?? '—' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Generated by KlassApp · {{ date('d M Y') }}
    </div>
</body>
</html>
