// Batch two: shared add / edit person form (student, teacher, parent, staff)
(() => {
const { SCHOOL, T, S, P, av, ic } = KD;
const ST = window.ST;
const f = (id, label, o = {}) => { const err = ST.state === 'error' && o.err; const v = ST.mode === 'edit' && o.v != null ? o.v : '';
  const ctl = o.type === 'select' ? `<select class="inp sel" id="${id}" ${err ? `aria-invalid="true" aria-describedby="${id}-e"` : ''}>${(o.opts || []).map((x, i) => `<option ${(ST.mode === 'edit' && x === o.v) || (!i && o.ph) ? 'selected' : ''}>${x}</option>`).join('')}</select>`
    : o.type === 'textarea' ? `<textarea class="inp" id="${id}" rows="3" ${o.hint ? `aria-describedby="${id}-h"` : ''}>${v}</textarea>`
    : `<input class="inp" id="${id}" type="${o.type || 'text'}" value="${err ? '' : v}" ${o.ac ? `autocomplete="${o.ac}"` : ''} ${o.ph2 ? `placeholder="${o.ph2}"` : ''} ${err ? `aria-invalid="true" aria-describedby="${id}-e"` : o.hint ? `aria-describedby="${id}-h"` : ''}>`;
  return `<div class="f${o.full ? ' full' : ''}${err ? ' err' : ''}"><label for="${id}">${label}${o.opt ? '<span class="opt">Optional</span>' : ''}</label>${ctl}${err ? `<span class="emsg" id="${id}-e">${ic('circle-alert', 'ic ic-sm')}${o.err}</span>` : o.hint ? `<span class="hint" id="${id}-h">${o.hint}</span>` : ''}</div>`; };
const radios = (name, label, opts, o = {}) => `<fieldset class="f${o.full ? ' full' : ''}"><legend>${label}${o.opt ? '<span class="opt">Optional</span>' : ''}</legend><div class="radios">${opts.map((x, i) => `<label class="rc"><input type="radio" name="${name}" ${(o.sel != null && i === o.sel) ? 'checked' : ''}>${x}</label>`).join('')}</div>${o.hint ? `<span class="hint">${o.hint}</span>` : ''}</fieldset>`;
const check = (label, on, hint) => `<label class="rc ck full"><input type="checkbox" ${on ? 'checked' : ''}><span>${label}${hint ? `<span class="hint" style="display:block">${hint}</span>` : ''}</span></label>`;
const sec = (t, p, body) => `<section class="fsec"><h2>${t}</h2>${p ? `<p class="hint" style="margin:-8px 0 0">${p}</p>` : ''}<div class="fg">${body}</div></section>`;
const nameRow = (p, err) => f('fn', 'First name', { ac: 'given-name', v: p && p.fn }) + f('ln', 'Last name', { ac: 'family-name', v: p && p.ln, err: err ? 'Enter a last name' : null });
const photo = p => `<div class="f full"><span class="lab">Photo<span class="opt">Optional</span></span><div class="phrow">${p ? av(p, 64) : '<span class="av" style="width:64px;height:64px;background:#F1F5F9;color:#475569;border:1px dashed #94A3B8" aria-hidden="true">' + ic('camera') + '</span>'}<span style="display:flex;flex-direction:column;gap:4px"><a class="btn" href="#">${ic('upload')}${p ? 'Change photo' : 'Upload photo'}</a><span class="hint">Until there's a photo, KlassApp shows initials.</span></span></div></div>`;
function invite(kind, edit) {
  if (edit) { const st = kind === 'parent' ? 'Opted in to WhatsApp on 12 Sep 2026' : 'Joined on 3 Sep 2026';
    return sec(kind === 'parent' ? 'WhatsApp and login' : 'Login', '', `<div class="f full"><div class="reqrow"><span class="badge b-ok">${st}</span>${kind === 'parent' ? '<a class="btn" href="#">Send a login invite by email</a>' : '<a class="btn" href="#">Reset password</a>'}</div></div>`); }
  if (kind === 'parent') return sec('Invite', 'Parents get report cards, fee balances and attendance on WhatsApp once they reply to the opt-in message.',
    check('Send a WhatsApp opt-in message after saving', true, 'Sent to the phone number above. They reply YES to start receiving messages.') + check('Also send a login invite by email', false, 'For parents who also want to use the web app. Needs an email address.'));
  return sec('Invite', 'They choose their own password. The invite link works for 72 hours.',
    radios('inv', 'Send an invite', ['By email', 'By WhatsApp', 'Not yet'], { sel: 0, full: 1, hint: 'You can send or resend it later from their profile.' }));
}
const SPEC = {
  student: { t: 'student', p: () => S[0], body: (p, e) => [
    sec('Student', '', nameRow(p, e) + radios('gender', 'Gender', ['Female', 'Male', 'Not specified'], { sel: ST.mode === 'edit' ? 0 : 2 }) + f('dob', 'Date of birth', { type: 'date', opt: 1, v: '2015-03-14' }) + photo(ST.mode === 'edit' ? p : null)),
    sec('Class', '', f('cls', 'Class', { type: 'select', opts: ['Choose a class', 'Nursery', 'Reception', 'Primary 1', 'Primary 2', 'Primary 3', 'Primary 4', 'Primary 5', 'Primary 6'], ph: 1, v: 'Primary 5' }) + f('str', 'Stream', { type: 'select', opts: ['Choose a stream', 'Blue', 'Red'], ph: 1, v: 'Blue', hint: 'Shown only for classes with streams.' }) + f('jd', 'Joining date', { type: 'date', v: '2024-01-12', hint: ST.mode === 'edit' ? '' : 'Defaults to today.' }) + `<div class="f"><span class="lab">KLS number</span><span class="ro">${ST.mode === 'edit' ? p.kls : 'Created when you save'}</span><span class="hint">KLS + your school's number (${SCHOOL.no}) + a 4-digit sequence. It never changes.</span></div>`),
    ST.mode === 'edit' ? sec('Parents and guardians', '', `<div class="f full"><div class="reqrow"><span class="tch" style="display:flex;gap:10px;align-items:center">${av(P[0], 40)}<span><b>${P[0].fn} ${P[0].ln}</b><span class="sub">Mother · ${P[0].ph}</span></span></span><a class="btn" href="#">${ic('link')}Link another</a></div></div>`)
      : sec('Parent or guardian', 'Link an existing parent, or add a new one. Parents receive updates on WhatsApp.', `<div class="f full"><label for="ps">Find a parent already in KlassApp<span class="opt">Optional</span></label><span class="search" style="flex:none">${ic('search')}<input class="inp" id="ps" type="search" placeholder="Search by name or phone" style="padding-left:40px"></span></div><p class="or full">Or add a new parent</p>` + f('pfn', 'First name') + f('pln', 'Last name') + f('rel', 'Relationship to the student', { type: 'select', opts: ['Choose', 'Mother', 'Father', 'Guardian', 'Other'], ph: 1 }) + f('pph', 'Phone', { type: 'tel', ac: 'tel', err: e ? 'Enter a phone number so the parent can get WhatsApp updates' : null, hint: 'Include the country code.' }) + check('This number is on WhatsApp', true) + check('Send a WhatsApp opt-in message after saving', true)),
    sec('Health and support', 'Only admins and the head teacher can see this. Each view is logged.', f('al', 'Allergies or medical conditions', { type: 'textarea', opt: 1, full: 1, v: 'Peanuts (severe). Mild asthma.' }) + f('sn', 'Support needs', { type: 'textarea', opt: 1, full: 1, v: 'Sits near the front for hearing.' }))] },
  teacher: { t: 'teacher', p: () => T[0], body: (p, e) => [
    sec('Teacher', '', nameRow(p, e) + f('role', 'Role', { type: 'select', opts: ['Teacher', 'Head teacher', 'Deputy head teacher'], v: 'Teacher' }) + f('sno', 'Staff number', { opt: 1, hint: 'If your school uses one.' }) + f('ph', 'Phone', { type: 'tel', ac: 'tel', v: p.ph, hint: 'Include the country code.' }) + f('em', 'Email', { type: 'email', ac: 'email', v: p.email, err: e ? 'Enter an email or a phone number to send the invite' : null }) + photo(ST.mode === 'edit' ? p : null)),
    sec('Teaching', 'You can also do this later from the class or subject page.', `<div class="f full"><span class="lab">Classes and subjects<span class="opt">Optional</span></span><ul class="assign">${(ST.mode === 'edit' ? [['Primary 5 · Blue', 'Mathematics'], ['Primary 5 · Blue', 'Science'], ['Primary 6 · Blue', 'Mathematics']] : [['Primary 5 · Blue', 'Mathematics']]).map((r, i) => `<li><select class="inp sel" aria-label="Class ${i + 1}"><option>${r[0]}</option></select><select class="inp sel" aria-label="Subject ${i + 1}"><option>${r[1]}</option></select><button class="btn icon" type="button" aria-label="Remove ${r[1]}, ${r[0]}">${ic('x')}</button></li>`).join('')}</ul><a class="btn" href="#" style="align-self:flex-start">${ic('plus')}Add a class and subject</a></div>` + f('ct', 'Class teacher of', { type: 'select', opt: 1, opts: ['None', 'Primary 5 · Blue', 'Primary 5 · Red', 'Primary 6 · Blue'], v: 'Primary 5 · Blue' })),
    invite('teacher', ST.mode === 'edit')] },
  parent: { t: 'parent', p: () => P[0], body: (p, e) => [
    sec('Parent or guardian', '', nameRow(p, e) + f('ph', 'Phone', { type: 'tel', ac: 'tel', v: p.ph, hint: 'Include the country code.' }) + f('em', 'Email', { type: 'email', ac: 'email', opt: 1, v: p.email }) + check('This number is on WhatsApp', true) + photo(ST.mode === 'edit' ? p : null)),
    sec('Children', '', `<div class="f full"><label for="ks">Link a child</label><span class="search" style="flex:none">${ic('search')}<input class="inp" id="ks" type="search" placeholder="Search by name or KLS number" style="padding-left:40px"></span>${ST.state === 'error' ? `<span class="emsg">${ic('circle-alert', 'ic ic-sm')}Link at least one child</span>` : ''}<ul class="kids">${(ST.mode === 'edit' || ST.state !== 'error' ? p.kids : []).map(k => `<li>${av(k, 32)}<span style="min-width:0"><b>${k.fn} ${k.ln}</b><span class="sub">${k.cls} · ${k.kls}</span></span><select class="inp sel" aria-label="Relationship to ${k.fn}"><option>Mother</option><option>Father</option><option>Guardian</option><option>Other</option></select><button class="btn icon" type="button" aria-label="Unlink ${k.fn}">${ic('x')}</button></li>`).join('')}</ul></div>`),
    invite('parent', ST.mode === 'edit')] },
  staff: { t: 'staff member', p: () => ({ id: 3310, fn: 'Ruth', ln: 'Kim', ph: '+000 700 100 120', email: 'r.kim@demojunior.school' }), body: (p, e) => [
    sec('Staff member', 'For non-teaching staff, such as the bursar or librarian. Their role decides what they can see.', nameRow(p, e) + f('role', 'Role', { type: 'select', opts: ['Choose a role', 'Bursar', 'Librarian', 'School admin', 'Office staff'], ph: 1, v: 'Bursar' }) + f('sno', 'Staff number', { opt: 1 }) + f('ph', 'Phone', { type: 'tel', ac: 'tel', v: p.ph }) + f('em', 'Email', { type: 'email', ac: 'email', v: p.email }) + photo(ST.mode === 'edit' ? p : null))] } };
window.scrForm = kind => {
  const k = SPEC[kind], p = k.p(), edit = ST.mode === 'edit', e = ST.state === 'error';
  const back = { student: 'students', teacher: 'teachers', parent: 'parents', staff: 'teachers' }[kind];
  const title = edit ? `Edit ${p.fn} ${p.ln}` : `Add ${k.t}`;
  const errs = e ? { student: ['Last name', 'Parent phone'], teacher: ['Last name', 'Email'], parent: ['Last name', 'Children'], staff: ['Last name'] }[kind] : null;
  return `<nav aria-label="Breadcrumb" style="font-size:14px"><a href="#" data-go="${back}">${back === 'teachers' ? 'Teachers and staff' : back[0].toUpperCase() + back.slice(1)}</a> <span aria-hidden="true">›</span> ${edit ? p.fn + ' ' + p.ln : 'Add'}</nav>
  <div class="ph"><div><h1>${title}</h1><p>${edit ? 'Changes save when you press Save.' : 'Fields are required unless marked Optional.'}</p></div></div>
  <form class="form" novalidate onsubmit="return false">${errs ? `<div class="errsum" role="alert" tabindex="-1"><b>${errs.length} things need fixing</b><ul>${errs.map(x => `<li><a href="#">${x}</a></li>`).join('')}</ul></div>` : ''}
  ${k.body(p, e).join('')}
  <div class="fbar"><a class="btn" href="#" data-go="${back}">Cancel</a>${edit ? '' : '<button class="btn" type="button">Save and add another</button>'}<button class="btn pri" type="submit">${edit ? 'Save changes' : kind === 'student' ? 'Add student' : `Save${kind === 'parent' ? ' and send opt-in' : kind === 'teacher' ? ' and send invite' : ''}`}</button></div></form>`;
};
})();
