// Profiles: student, teacher, parent — admin viewer
(() => {
const { SCHOOL, T, S, P, av, money, grade, ic } = KD;
const ST = window.ST;
const tabs = (list, cur) => `<div class="tabs" role="tablist">${list.map(x => `<button role="tab" type="button" data-act="tab" data-tab="${x}" aria-selected="${x === cur}">${x}</button>`).join('')}</div>`;
const more = (id, items) => `<span style="position:relative"><button class="btn icon" type="button" data-act="rmenu" data-id="${id}" aria-haspopup="menu" aria-expanded="${ST.menu == id}" aria-label="More actions">${ic('ellipsis')}</button>${ST.menu == id ? `<div class="rmenu" role="menu" style="top:calc(100% + 6px);right:0;width:240px">${items}</div>` : ''}</span>`;
const empty = (t, p, b) => `<div class="empty"><b>${t}</b><p>${p}</p>${b ? `<a class="btn" href="#">${b}</a>` : ''}</div>`;
const E = () => ST.state === 'empty';
/* ---------- 3. Student ---------- */
window.scrStudent = () => {
  const s = S[0], tl = ['Overview', 'Academics', 'Attendance', 'Fees', 'Parents and guardians', 'Health and support', 'Documents', 'Notes'], tab = tl.includes(ST.tab) ? ST.tab : 'Overview';
  const menu = `<a class="mi" role="menuitem" href="#">${ic('pencil')}Edit details</a><a class="mi" role="menuitem" href="#">${ic('key-round')}Reset password</a><a class="mi" role="menuitem" href="#">${ic('arrow-right-left')}Move to class</a><div class="sep" role="separator"></div>
   <button class="mi danger" role="menuitem" type="button" data-act="dlg" data-k="deact">${ic('user-x')}Deactivate student</button>`;
  const hd = `<nav aria-label="Breadcrumb" style="font-size:14px"><a href="#" data-go="students">Students</a> <span aria-hidden="true">›</span> ${s.fn} ${s.ln}</nav>
  <div class="phd">${av(s, ST.mob ? 64 : 112)}<div style="min-width:0"><h1>${s.fn} ${s.ln}</h1><div class="meta"><a href="#" data-go="class" style="font-weight:700">${s.cls}</a><span><span class="k">KLS</span> <span style="font-variant-numeric:tabular-nums">${s.kls}</span></span><span class="badge b-ok">Active</span></div></div>
  <div class="row-acts"><a class="btn" href="#">${ic('pencil')}Edit</a><a class="btn" href="#">${ic('message-circle')}Message parent</a>${more('stu', menu)}</div></div>`;
  const k = E() ? `<div class="kpis k3"><div class="kpi"><span class="l">${ic('calendar-check', 'ic ic-sm')}Attendance this term</span><span class="v">–</span><span class="s">No register taken yet</span></div><div class="kpi"><span class="l">${ic('chart-column', 'ic ic-sm')}Latest exam</span><span class="v">–</span><span class="s">No marks yet</span></div><div class="kpi"><span class="l">${ic('wallet', 'ic ic-sm')}Fees</span><span class="v">–</span><span class="s">No fee structure</span></div></div>`
    : `<div class="kpis k3"><div class="kpi"><span class="l">${ic('calendar-check', 'ic ic-sm')}Attendance this term</span><span class="v">91%</span><span class="meter" role="img" aria-label="91%"><i style="width:91%"></i></span><span class="s">5 days absent · 2 late</span></div>
     <div class="kpi"><span class="l">${ic('chart-column', 'ic ic-sm')}Latest exam · Mid-term</span><span class="v">74% · B</span><span class="s">6th of 32 in Primary 5 · Blue</span></div>
     <div class="kpi"><span class="l">${ic('wallet', 'ic ic-sm')}Fees · ${SCHOOL.term}</span><span class="kl">Balance</span><span class="v owed">${money(180000)}</span><span class="s"><span class="badge b-warn">Partly paid</span> ${money(270000)} of ${money(450000)}</span></div></div>`;
  let b;
  if (tab === 'Overview') b = `<div class="grid2"><div class="card"><h2>Student</h2><dl class="kv"><dt>Full name</dt><dd>${s.fn} ${s.ln}</dd><dt>KLS number</dt><dd>${s.kls}</dd><dt>Class</dt><dd>${s.cls}</dd><dt>Gender</dt><dd>Female</dd><dt>Date of birth</dt><dd>${E() ? '<span style="color:var(--d-text-secondary)">Not given</span>' : s.dob}</dd><dt>Joined</dt><dd>${E() ? 'This term' : 'Term 1, 2024'}</dd></dl></div>
   <div class="card"><h2>Parents and guardians</h2>${E() ? `<p style="margin:0">No parent linked yet.</p><a class="btn" href="#" style="align-self:flex-start">${ic('link')}Link a parent</a>` : `<div class="kidc">${av(P[0], 40)}<div><a href="#" data-go="parent" style="font-weight:700">${P[0].fn} ${P[0].ln}</a><div class="pc-sub" style="font-size:13.5px;color:var(--d-text-secondary)">Mother · <a href="tel:+000772418205">${P[0].ph}</a> · on WhatsApp</div></div></div>`}</div></div>`;
  else if (E()) b = { Academics: empty('No marks yet', 'Marks appear here once teachers enter them for an exam.'), Attendance: empty('No attendance taken yet this term', 'It appears after the class teacher takes the first register.'), Fees: empty('No fee structure for Primary 5 this term', 'Set up the term’s fees before recording payments.', 'Set up fees'), 'Parents and guardians': empty('No parent linked yet', 'Link a parent so they receive report cards and fee messages on WhatsApp.', 'Link a parent'), 'Health and support': empty('No health or support notes', 'Parents can add allergies, medical conditions and support needs on the admission form, or you can add them here.', 'Add notes'), Documents: empty('No documents yet', 'Birth certificates and photos sent with the admission form appear here.', 'Upload document'), Notes: empty('No notes', 'Notes are visible to admins only, and each view is logged.', 'Add a note') }[tab];
  else if (tab === 'Academics') { const sub = [['English', 70, 72, 76], ['Mathematics', 66, 71, 73], ['Science', 74, 75, 79], ['Social Studies', 62, 66, 68], ['Religious Education', 81, 80, 84], ['Creative Arts', 77, 79, 0]];
    b = `<div class="card"><div class="hd"><h2>Marks by subject</h2><small>${SCHOOL.year} · % per exam</small></div><div class="scroll-x"><table class="dt"><thead><tr><th scope="col">Subject</th><th class="n" scope="col">Term 1</th><th class="n" scope="col">Term 2</th><th class="n" scope="col">Term 3 mid-term</th><th scope="col">Grade</th></tr></thead><tbody>${sub.map(r => `<tr><td>${r[0]}</td><td class="n">${r[1]}</td><td class="n">${r[2]}</td><td class="n">${r[3] || '<span style="color:var(--d-text-secondary)">Pending</span>'}</td><td>${r[3] ? grade(r[3]) : '–'}</td></tr>`).join('')}<tr><th scope="row">Average</th><td class="n"><b>72</b></td><td class="n"><b>74</b></td><td class="n"><b>74</b></td><td><b>B</b></td></tr></tbody></table></div></div>
    <div class="card"><div class="hd"><h2>This term against the class</h2><small>Amara · class average</small></div><div class="hbars">${sub.filter(r => r[3]).map((r, i) => `<div class="hb"><span>${r[0].split(' ')[0]}</span><span class="t" role="img" aria-label="${r[0]}: ${r[3]}%, class average ${r[3] - 5 + i}%"><i style="width:${r[3]}%"></i></span><b>${r[3]}%</b></div><div class="hb" style="margin-top:-6px"><span></span><span class="t" style="height:6px" aria-hidden="true"><i style="width:${r[3] - 5 + i}%;background:#94A3B8"></i></span><span style="font-size:12px;text-align:right;color:var(--d-text-secondary)">${r[3] - 5 + i}%</span></div>`).join('')}</div><div class="legend"><span><i style="background:#1E6FD9"></i>Amara</span><span><i style="background:#94A3B8"></i>Class average</span></div></div>`; }
  else if (tab === 'Attendance') b = `<div class="card"><div class="hd"><h2>${SCHOOL.term}</h2><small>Marked by Sarah Nakato</small></div><div class="kpis k3"><div class="kpi"><span class="l">Present</span><span class="v">91%</span></div><div class="kpi"><span class="l">Absent</span><span class="v">5 days</span></div><div class="kpi"><span class="l">Late</span><span class="v">2 days</span></div></div><table class="dt"><thead><tr><th scope="col">Date</th><th scope="col">Status</th></tr></thead><tbody><tr><td>Mon 5 Oct</td><td><span class="badge b-bad">Absent</span></td></tr><tr><td>Fri 2 Oct</td><td><span class="badge b-ok">Present</span></td></tr><tr><td>Thu 1 Oct</td><td><span class="badge b-warn">Late</span></td></tr></tbody></table></div>`;
  else if (tab === 'Fees') b = `<div class="card"><div class="hd"><h2>${SCHOOL.term}, ${SCHOOL.year}</h2><span class="badge b-warn">Partly paid</span></div><dl class="kv"><dt>Expected</dt><dd>${money(450000)}</dd><dt>Paid</dt><dd>${money(270000)}</dd><dt>Balance</dt><dd class="owed"><b>${money(180000)}</b></dd></dl><table class="dt"><thead><tr><th scope="col">Date</th><th scope="col">Method</th><th class="n" scope="col">Amount</th></tr></thead><tbody><tr><td>2 Sep</td><td>Bank transfer</td><td class="n">${money(270000)}</td></tr></tbody></table><div class="row-acts"><a class="btn pri" href="#">Record payment</a><a class="btn" href="#">Send reminder on WhatsApp</a></div></div>`;
  else if (tab === 'Parents and guardians') b = `<div class="card"><div class="hd"><h2>Parents and guardians</h2><a class="btn" href="#">${ic('link')}Link another</a></div><div class="kidc">${av(P[0], 48)}<div><a href="#" data-go="parent" style="font-weight:700">${P[0].fn} ${P[0].ln}</a><div style="font-size:13.5px;color:var(--d-text-secondary)">Mother · primary contact</div><a class="ctline" href="tel:+000772418205">${ic('phone')}${P[0].ph}</a><span class="badge b-ok">Opted in to WhatsApp</span></div></div></div>`;
  else if (tab === 'Documents') b = `<div class="card"><div class="hd"><h2>Documents</h2><a class="btn" href="#">${ic('upload')}Upload</a></div><table class="dt"><thead><tr><th scope="col">Document</th><th scope="col">From</th><th scope="col">Added</th></tr></thead><tbody><tr><td>${ic('file-text', 'ic ic-sm')} Birth certificate.pdf</td><td>Admission form</td><td>12 Jan 2024</td></tr><tr><td>${ic('image', 'ic ic-sm')} Passport photo.jpg</td><td>Admission form</td><td>12 Jan 2024</td></tr></tbody></table></div>`;
  else if (tab === 'Health and support') b = `<div class="card"><div class="hd"><h2>Health and support</h2><span class="badge b-info">${ic('lock-keyhole', 'ic ic-sm')}Admins and head teacher only</span></div><p class="note">${ic('history', 'ic ic-sm')}Opening this tab is logged. Last opened by Mucunguzi Moses today at 09:14.</p><dl class="kv"><dt>Allergies</dt><dd>Peanuts (severe). Carries an adrenaline pen in her school bag.</dd><dt>Medical conditions</dt><dd>Mild asthma. Inhaler kept at the school office.</dd><dt>Support needs</dt><dd>Sits near the front of the class for hearing.</dd><dt>Emergency contact</dt><dd>Grace Okafor (mother) · <a href="tel:+000772418205">${P[0].ph}</a></dd><dt>Last updated</dt><dd>12 Jan 2024 · admission form</dd></dl><div class="row-acts"><a class="btn" href="#">${ic('pencil')}Edit notes</a></div></div>`;
  else b = `<div class="card"><div class="reqrow"><span>Notes are visible to admins only. Opening them is logged.</span><button class="btn" type="button">${ic('lock-keyhole-open')}Show notes</button></div></div>`;
  return hd + k + `<div class="tabw">${tabs(tl, tab)}</div>` + b;
};
/* ---------- 4. Teacher ---------- */
window.scrTeacher = () => {
  const inv = ST.invite || 'accepted', t = { ...T[0], invite: inv };
  const badge = inv === 'accepted' ? '<span class="badge b-ok">Joined 3 Sep 2026</span>' : inv === 'invited' ? '<span class="badge b-info">Invited 5 Oct · not accepted yet</span>' : '<span class="badge b-warn">Not invited</span>';
  const invBtn = inv === 'accepted' ? '' : inv === 'invited' ? `<a class="btn" href="#">${ic('send')}Resend invite</a>` : `<a class="btn pri" href="#">${ic('send')}Send invite</a>`;
  const menu = `<a class="mi" role="menuitem" href="#">${ic('pencil')}Edit details</a><a class="mi" role="menuitem" href="#">${ic('book-open')}Assign classes and subjects</a>${inv === 'accepted' ? `<a class="mi" role="menuitem" href="#">${ic('key-round')}Reset password</a>` : ''}<div class="sep" role="separator"></div><button class="mi danger" role="menuitem" type="button" data-act="dlg" data-k="deactT">${ic('user-x')}Deactivate account</button>`;
  return `<nav aria-label="Breadcrumb" style="font-size:14px"><a href="#" data-go="teachers">Teachers</a> <span aria-hidden="true">›</span> ${t.fn} ${t.ln}</nav>
  <div class="phd">${av(t, ST.mob ? 64 : 112)}<div style="min-width:0"><h1>${t.fn} ${t.ln}</h1><div class="meta"><span class="badge b-info">${t.role}</span><span>Class teacher of <a href="#" data-go="class" style="font-weight:700">${t.ctOf}</a></span>${badge}</div></div>
  <div class="row-acts">${invBtn}<a class="btn" href="#">${ic('pencil')}Edit</a>${more('tch', menu)}</div></div>
  <div class="kpis k4">
   <div class="kpi"><span class="l">${ic('school', 'ic ic-sm')}Classes</span><span class="v">2</span><span class="s">Primary 5 · Blue, Primary 6 · Blue</span></div>
   <div class="kpi"><span class="l">${ic('book-open', 'ic ic-sm')}Subjects</span><span class="v">2</span><span class="s">Mathematics, Science</span></div>
   ${ST.wl === 'as' ? `<div class="kpi"><span class="l">${ic('clock', 'ic ic-sm')}Workload</span><span class="v">3</span><span class="s">class–subject assignments</span><span class="badge b-off" style="align-self:flex-start">No timetable yet</span></div>` : `<div class="kpi"><span class="l">${ic('clock', 'ic ic-sm')}Workload</span><span class="v">${t.lessons}</span><span class="s">lessons a week</span><span class="badge b-ok" style="align-self:flex-start">From the timetable</span></div>`}
   <div class="kpi"><span class="l">${ic('circle-alert', 'ic ic-sm')}Still pending</span><span class="v">1</span><span class="s warn">Science marks · Primary 5 Blue</span></div></div>
  <div class="grid3"><div class="card"><div class="hd"><h2>Teaches</h2><small>${SCHOOL.term}</small></div><div class="scroll-x"><table class="dt"><thead><tr><th scope="col">Class</th><th scope="col">Subject</th><th class="n" scope="col">Students</th><th scope="col">Mid-term marks</th></tr></thead><tbody>
   <tr><td><a href="#" data-go="class">Primary 5 · Blue</a> <span class="badge b-ok">Class teacher</span></td><td>Mathematics</td><td class="n">32</td><td><span class="badge b-ok">Entered</span></td></tr>
   <tr><td><a href="#" data-go="class">Primary 5 · Blue</a></td><td>Science</td><td class="n">32</td><td><span class="badge b-warn">Pending</span></td></tr>
   <tr><td>Primary 6 · Blue</td><td>Mathematics</td><td class="n">27</td><td><span class="badge b-ok">Entered</span></td></tr></tbody></table></div>
   <div class="reqrow"><span>Today's attendance for Primary 5 · Blue</span><span class="badge b-ok">Taken at 08:12</span></div></div>
   <div class="card"><h2>Contact</h2><a class="ctline" href="tel:+000700100101">${ic('phone')}${t.ph}</a><a class="ctline trunc" href="mailto:${t.email}">${ic('mail')}<span class="trunc">${t.email}</span></a><dl class="kv" style="margin-top:4px"><dt>Last login</dt><dd>${inv === 'accepted' ? t.last : 'Never'}</dd><dt>Account</dt><dd>${inv === 'accepted' ? 'Active' : inv === 'invited' ? 'Invite sent, link valid 72 hours' : 'No login yet'}</dd></dl></div></div>`;
};
/* ---------- 5. Parent ---------- */
window.scrParent = () => {
  const p = P[0], waSt = ST.wa || 'in';
  const waRow = waSt === 'in' ? `<span class="badge b-ok">Opted in on ${p.waDate}</span>` : waSt === 'pending' ? `<span class="badge b-info">Opt-in request sent, waiting for reply</span>` : `<span class="badge b-off">Not opted in</span><a class="btn" href="#">${ic('message-circle')}Send opt-in request</a>`;
  const menu = `<a class="mi" role="menuitem" href="#">${ic('pencil')}Edit details</a><a class="mi" role="menuitem" href="#">${ic('link')}Link a child</a><a class="mi" role="menuitem" href="#">${ic('key-round')}Reset password</a><div class="sep" role="separator"></div><button class="mi danger" role="menuitem" type="button" data-act="dlg" data-k="deactP">${ic('user-x')}Deactivate account</button>`;
  const kids = E() ? empty('No children linked yet', 'Link this parent to their children so they receive report cards and fee messages on WhatsApp.', 'Link a child')
    : `<div class="grid2">${p.kids.map(k => `<article class="card"><div class="kidc">${av(k, 48)}<div style="min-width:0"><a href="#" data-go="student" style="font:600 16px var(--d-font-display,'Sora',sans-serif);color:#0F172A">${k.fn} ${k.ln}</a><div style="font-size:13.5px;color:var(--d-text-secondary)">${k.cls} · <span style="font-variant-numeric:tabular-nums">${k.kls}</span></div><div class="meta" style="margin-top:6px;font-size:13.5px"><span>Attendance ${k.att}%</span>${k.bal ? `<span class="owed">${money(k.bal)} due</span>` : '<span class="badge b-ok">Fees cleared</span>'}</div></div>
     <div class="ql"><a class="btn" href="#">${ic('file-text')}Report card</a><a class="btn" href="#">${ic('wallet')}Fees</a></div></div></article>`).join('')}</div>`;
  return `<nav aria-label="Breadcrumb" style="font-size:14px"><a href="#" data-go="parents">Parents</a> <span aria-hidden="true">›</span> ${p.fn} ${p.ln}</nav>
  <div class="phd">${av(p, ST.mob ? 64 : 112)}<div style="min-width:0"><h1>${p.fn} ${p.ln}</h1><div class="meta"><span class="badge b-info">Parent</span><span>${E() ? 'No children linked' : p.kids.length + ' children at ' + SCHOOL.name}</span></div></div>
  <div class="row-acts"><a class="btn" href="#">${ic('message-circle')}Message on WhatsApp</a><a class="btn" href="#">${ic('pencil')}Edit</a>${more('par', menu)}</div></div>
  <h2 style="font:600 18px var(--d-font-display,'Sora',sans-serif);margin:0;color:#0F172A">Children</h2>${kids}
  <div class="grid2"><div class="card"><h2>Contact</h2><a class="ctline" href="tel:+000772418205">${ic('phone')}${p.ph}</a><a class="ctline" href="mailto:${p.email}">${ic('mail')}<span class="trunc">${p.email}</span></a></div>
  <div class="card"><h2>WhatsApp and access</h2><div class="reqrow">${waRow}</div><dl class="kv"><dt>Last login</dt><dd>${p.last}</dd><dt>Messages this term</dt><dd>12 sent · 2 replies</dd></dl></div></div>`;
};
})();
