
# =========================
# LOCAL DEVELOPMENT
# =========================

# server {
#     listen 80;
#     server_name localhost;

#     root /var/www/public;
#     index index.php index.html;

#     location / {
#         try_files $uri $uri/ /index.php?$query_string;
#     }

#     location ~ \.php$ {
#         fastcgi_pass sms-app:9000;
#         fastcgi_index index.php;
#         include fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#     }

#     location ~ /\.ht {
#         deny all;
#     }
# }

# =========================
# PRODUCTION
# =========================

# HTTP -> HTTPS SERVER ========= KLASS APP ========
server { 
    listen 80;
    server_name klassapp.xyz www.klassapp.xyz;

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTP -> HTTPS SERVER ========= hfhcd APP ========
# server {
#     listen 80;
#     server_name hfhcd.org www.hfhcd.org;
#     return 301 https://$host$request_uri;
#  };

# =====================================================
# 2. KLASSAPP (LARAVEL) HTTPS SERVER
# =====================================================

    server {
        listen 443 ssl;
        server_name klassapp.xyz www.klassapp.xyz;

        ssl_certificate /etc/letsencrypt/live/klassapp.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/klassapp.xyz/privkey.pem;

        # Security headers
       add_header X-Frame-Options "SAMEORIGIN" always;
       add_header X-Content-Type-Options "nosniff" always;
       add_header Referrer-Policy "strict-origin-when-cross-origin" always;

       root /var/www/public;
       index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    # ========================= MAIN REQUEST HANDLING
        location ~ \.php$ {
            include fastcgi_params;
            # fastcgi_pass sms-app:9000;
            fastcgi_pass app:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }

         # Static files caching
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public";
        access_log off;
    }
    }

# =====================================================
# 3. HFHCD (WORDPRESS) HTTPS SERVER
# =====================================================

#     server {
#     listen 443 ssl;
#     server_name hfhcd.org www.hfhcd.org;
#     # ssl part
#     ssl_certificate /etc/letsencrypt/live/hfhcd.org/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/hfhcd.org/privkey.pem;

#     client_max_body_size 64m;
#     # Security headers
#     add_header X-Frame-Options "SAMEORIGIN" always;
#     add_header X-Content-Type-Options "nosniff" always;
#     add_header Referrer-Policy "strict-origin-when-cross-origin" always;

#     # main proxy to wordpress
#     location / {
#             proxy_pass http://127.0.0.1:8090;
#             include proxy_params;

#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;

#             proxy_redirect off;
#         }


#     # Cache common static assets at the edge.
#     location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|webp|woff|woff2|ttf)$ {
#        proxy_pass http://127.0.0.1:8090;
#         expires 7d;
#         add_header Cache-Control "public, max-age=604800, immutable";
#         access_log off;
#     }

#     location ~ /\.ht {
#         deny all;
#     }
# }

    