<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; color: #1a1a1a; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #2563EB; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { font-size: 18px; color: #2563EB; margin: 0 0 5px; }
        .header h2 { font-size: 14px; color: #4B5563; margin: 0; }
        .info-table { width: 100%; margin-bottom: 20px; border-collapse: collapse; }
        .info-table td { padding: 4px 8px; }
        .info-label { font-weight: bold; color: #4B5563; width: 120px; }
        table.marks { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.marks th { background: #2563EB; color: white; padding: 8px 12px; text-align: left; font-size: 11px; }
        table.marks td { padding: 8px 12px; border-bottom: 1px solid #E5E7EB; }
        table.marks tr:nth-child(even) { background: #F9FAFB; }
        .not-available { color: #DC2626; font-style: italic; font-size: 11px; }
        .footer { text-align: center; color: #9CA3AF; font-size: 10px; margin-top: 30px; padding-top: 15px; border-top: 1px solid #E5E7EB; }
        .badge-partial { display: inline-block; background: #FEF3C7; color: #92400E; padding: 3px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $school->name ?? 'School' }}</h1>
        <h2>Report Card — {{ $term->name ?? '' }}</h2>
    </div>

    <table class="info-table">
        <tr><td class="info-label">Student Name:</td><td>{{ $student->displayName }}</td></tr>
        <tr><td class="info-label">Class:</td><td>{{ $student->studentAcademic?->first()?->standardLink?->standard?->name ?? $student->studentAcademic?->standardLink?->standard?->name ?? 'N/A' }}</td></tr>
        <tr><td class="info-label">Term:</td><td>{{ $term->name ?? 'N/A' }}</td></tr>
    </table>

    @if(!empty($partial))
        <p><span class="badge-partial">⚠ Some subjects not yet finalized</span></p>
    @endif

    <table class="marks">
        <thead>
            <tr>
                <th>Subject</th>
                <th>Score</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody>
            @forelse($marksData as $m)
                <tr>
                    <td>{{ $m['subject'] }}</td>
                    <td>
                        @if($m['approved'])
                            {{ $m['score'] }}%
                        @else
                            <span class="not-available">Not yet available</span>
                        @endif
                    </td>
                    <td>{{ $m['approved'] ? ($m['grade'] ?? '—') : '—' }}</td>
                </tr>
            @empty
                <tr><td colspan="3" style="text-align:center;padding:20px;color:#9CA3AF;">No results available for this term.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by KlassApp — {{ date('Y-m-d H:i') }}
    </div>
</body>
</html>
