// Batch two: Subjects, Subject page, Attendance overview, Exams (subject-first)
(() => {
const { SCHOOL, T, av, grade, ic } = KD;
const ST = window.ST; const { bars, line, kpi } = window.KC;
const tt = id => T.find(t => t.id === id);
const STREAMS = [['Primary 1', 'Blue', 't2', 16], ['Primary 1', 'Red', 't2', 15], ['Primary 2', 'Blue', 't3', 15], ['Primary 2', 'Red', 't3', 14], ['Primary 3', 'Blue', 't4', 28], ['Primary 4', 'Blue', 't5', 30], ['Primary 5', 'Blue', 't1', 16], ['Primary 5', 'Red', 't1', 16], ['Primary 6', 'Blue', 't6', 27]];
const SUB = [
  { id: 'eng', n: 'English', code: 'ENG', type: 'Core', lv: 'Primary 1–6', from: 0, tch: ['t2', 't3', 't6'], avg: 71, d: 2, ent: 9 },
  { id: 'mth', n: 'Mathematics', code: 'MTH', type: 'Core', lv: 'Primary 1–6', from: 0, tch: ['t1', 't5'], avg: 66, d: -1, ent: 6 },
  { id: 'sci', n: 'Science', code: 'SCI', type: 'Core', lv: 'Primary 3–6', from: 4, tch: ['t1', 't4'], avg: 72, d: 3, ent: 3 },
  { id: 'sst', n: 'Social Studies', code: 'SST', type: 'Core', lv: 'Primary 3–6', from: 4, tch: ['t4'], avg: 63, d: 0, ent: 5 },
  { id: 're', n: 'Religious Education', code: 'RE', type: 'Core', lv: 'Primary 1–6', from: 0, tch: ['t6'], avg: 79, d: 1, ent: 2, gap: 1 },
  { id: 'ca', n: 'Creative Arts', code: 'CA', type: 'Optional', lv: 'Primary 1–6', from: 0, tch: ['t7'], avg: null, d: 0, ent: 0 },
  { id: 'lan', n: 'Language', code: 'LAN', type: 'Core', lv: 'Nursery, Reception', nur: 1, tch: ['t7', 't8'] },
  { id: 'num', n: 'Numbers', code: 'NUM', type: 'Core', lv: 'Nursery, Reception', nur: 1, tch: ['t7', 't8'] },
  { id: 'rdg', n: 'Reading', code: 'RDG', type: 'Core', lv: 'Nursery, Reception', nur: 1, tch: ['t7', 't8'] }];
const rowsOf = s => s.nur ? [] : STREAMS.slice(s.from);
const stu = s => s.nur ? 46 : rowsOf(s).reduce((a, r) => a + r[3], 0);
const avs = ids => `<span class="avs">${ids.slice(0, 3).map(i => av(tt(i), 28)).join('')}${ids.length > 3 ? `<span class="sub">+${ids.length - 3}</span>` : ''}</span>`;
const prog = (a, b) => `<span class="prw"><span class="prog" role="progressbar" aria-valuemin="0" aria-valuemax="${b}" aria-valuenow="${a}" aria-label="${a} of ${b} classes"><i style="width:${b ? a / b * 100 : 0}%"></i></span><span class="sub">${a} of ${b}</span></span>`;
const stat = (a, b) => b === 0 ? '<span class="badge b-off">No exam</span>' : a === b ? '<span class="badge b-ok">Complete</span>' : a === 0 ? '<span class="badge b-off">Not started</span>' : '<span class="badge b-warn">In progress</span>';
const menu = (id, items) => `<span style="position:relative;display:inline-flex"><button class="btn icon ghost" type="button" data-act="rmenu" data-id="${id}" aria-haspopup="menu" aria-expanded="${ST.menu == id}" aria-label="More actions">${ic('ellipsis-vertical')}</button>${ST.menu == id ? `<div class="rmenu" role="menu" style="top:calc(100% + 4px);right:0">${items.map(m => m === '-' ? '<div class="sep" role="separator"></div>' : `<a class="mi${m.startsWith('!') ? ' danger' : ''}" role="menuitem" href="#" ${m === 'View subject' ? 'data-go="subject"' : ''}>${m.replace('!', '')}</a>`).join('')}</div>` : ''}</span>`;
const avgCell = s => s.nur ? '<span class="sub">Not examined</span>' : s.avg ? `<b>${s.avg}%</b> · ${grade(s.avg)} <span class="sub" style="display:inline">${s.d > 0 ? '▲ ' + s.d : s.d < 0 ? '▼ ' + -s.d : '–'}</span>` : '<span class="sub">No marks yet</span>';
/* ---------- Subjects index ---------- */
window.scrSubjects = () => {
  const head = `<div class="ph"><div><h1>Subjects</h1><p>${SUB.length} subjects · each listed once, across all its classes</p></div><div class="row-acts"><a class="btn pri" href="#" data-go="form-subject">${ic('plus')}Add subject</a></div></div>
  <div class="lt"><label class="search"><span class="sr">Search subjects</span>${ic('search')}<input type="search" placeholder="Search by subject or code"></label><div class="chips" role="group" aria-label="Filters"><button class="chip" type="button" aria-pressed="true">All <span class="n">9</span></button><button class="chip" type="button" aria-pressed="false">Core <span class="n">8</span></button><button class="chip" type="button" aria-pressed="false">Optional <span class="n">1</span></button><button class="chip" type="button" aria-pressed="false">Nursery <span class="n">3</span></button><button class="chip" type="button" aria-pressed="false">Primary <span class="n">6</span></button><button class="chip" type="button" aria-pressed="false">Missing a teacher <span class="n">1</span></button></div></div>`;
  if (ST.state === 'empty') return head + `<div class="empty"><b>No subjects yet</b><p>Add each subject once, then choose the classes that take it and who teaches it in each class.</p><a class="btn pri" href="#">${ic('plus')}Add subject</a></div>`;
  const M = ['View subject', 'Edit', 'Assign teachers', '-', '!Archive subject'];
  return head + `<div class="tbl"><table class="pl"><thead><tr><th scope="col">Subject</th><th scope="col">Type</th><th scope="col">Classes</th><th scope="col">Teachers</th><th scope="col">Average · Mid-term</th><th scope="col">Mid-term marks</th><th class="menu"><span class="sr">Actions</span></th></tr></thead><tbody>
  ${SUB.map(s => `<tr><td><span class="who"><span class="sic" aria-hidden="true">${s.code}</span><span style="min-width:0"><a href="#" data-go="subject">${s.n}</a><span class="sub">${s.code}</span></span></span></td><td>${s.type}</td><td>${s.nur ? 2 : rowsOf(s).length} <span class="sub" style="display:inline">· ${s.lv}</span>${s.gap ? ' <span class="badge b-warn">1 without a teacher</span>' : ''}</td><td>${avs(s.tch)}</td><td>${avgCell(s)}</td><td>${s.nur ? '<span class="badge b-off">No exam</span>' : prog(s.ent, rowsOf(s).length)}</td><td class="menu">${menu('s' + s.id, M)}</td></tr>`).join('')}</tbody></table>
  <div class="cards">${SUB.map(s => `<div class="pc nock"><span class="sic" aria-hidden="true">${s.code}</span><div style="min-width:0"><a class="nm trunc" href="#" data-go="subject">${s.n}</a><div class="ln2"><span>${s.lv}</span>${s.nur ? '' : stat(s.ent, rowsOf(s).length)}${s.gap ? '<span class="badge b-warn">1 without a teacher</span>' : ''}</div></div><div style="position:relative">${menu('m' + s.id, M)}</div></div>`).join('')}</div>
  <div class="pager"><span>Showing all 9</span></div></div>`;
};
/* ---------- Subject page ---------- */
window.scrSubject = () => {
  const s = SUB[1], rows = rowsOf(s);
  const st = (i, n) => i < 6 ? [n, n] : i === 6 ? [18, n] : [0, n];
  const EX = [['Beginning of term', '7 Sep', 9, 9, 64, 'Complete'], ['Mid-term', '5–9 Oct', 6, 9, 66, 'In progress'], ['End of term', 'From 24 Nov', 0, 9, null, 'Scheduled']];
  return `<nav aria-label="Breadcrumb" style="font-size:14px"><a href="#" data-go="subjects">Subjects</a> <span aria-hidden="true">›</span> ${s.n}</nav>
  <div class="ph"><div><h1>${s.n}</h1><div class="meta"><span class="badge b-info">${s.type}</span><span><span class="k">Code</span> ${s.code}</span><span>${s.lv}</span></div></div><div class="row-acts"><a class="btn" href="#">${ic('pencil')}Edit</a><a class="btn" href="#">${ic('user-round-plus')}Assign teachers</a>${menu('subj', ['Download all marksheets', '-', '!Archive subject'])}</div></div>
  <div class="kpis k4">${kpi('school', 'Classes', String(rows.length), s.lv)}<div class="kpi"><span class="l">${ic('presentation', 'ic ic-sm')}Teachers</span><span class="v">2</span><span class="s">${s.tch.map(i => tt(i).fn + ' ' + tt(i).ln).join(', ')}</span></div>${kpi('graduation-cap', 'Students', String(stu(s)), 'taking ' + s.n)}${kpi('chart-column', 'Average · Mid-term', '66% · C', '▼ 1 pt on Beginning of term', 'warn')}</div>
  <div class="card"><div class="hd"><h2>Exams this term</h2><small>${SCHOOL.term}, ${SCHOOL.year}</small></div>
  <ul class="exl">${EX.map((e, i) => `<li><span><b>${e[0]}</b><span class="sub">${e[1]}</span></span><span class="hm">${e[4] ? `Average <b>${e[4]}%</b>` : '<span class="sub">No marks yet</span>'}</span>${prog(e[2], e[3])}<span class="hm">${e[5] === 'Complete' ? '<span class="badge b-ok">Complete</span>' : e[5] === 'In progress' ? '<span class="badge b-warn">In progress</span>' : '<span class="badge b-off">Scheduled</span>'}</span><span class="row-acts">${i === 1 ? '<a class="btn pri" href="#">Enter marks</a>' : i === 0 ? '<a class="btn" href="#">View marks</a>' : ''}${menu('ex' + i, ['Import from spreadsheet', 'Download marksheet', 'Remind teachers'])}</span></li>`).join('')}</ul></div>
  <div class="grid3"><div class="card"><div class="hd"><h2>Classes</h2><small>Mid-term marks and report cards</small></div><div class="scroll-x"><table class="dt"><thead><tr><th scope="col">Class</th><th scope="col" class="hm">Teacher</th><th class="n hm" scope="col">Average</th><th scope="col">Marks</th><th scope="col" class="hm">Report card</th></tr></thead><tbody>
  ${rows.map((r, i) => { const [a, n] = st(i, r[3]); const t = tt(i > 5 ? 't1' : i < 4 ? 't5' : 't1'); return `<tr><td><a href="#" data-go="class">${r[0]} · ${r[1]}</a></td><td class="hm"><span class="tch" style="display:flex;gap:8px;align-items:center">${av(t, 24)}<span class="trunc">${t.fn} ${t.ln}</span></span></td><td class="n hm">${a === n ? 60 + (i * 5) % 14 + '%' : '–'}</td><td>${a === n ? `<span class="badge b-ok">Entered ${a}/${n}</span>` : a ? `<span class="badge b-warn">${a} of ${n}</span>` : `<span class="badge b-off">Not started</span>`}</td><td class="hm">${a === n ? '<span class="badge b-ok">Ready</span>' : '<span class="sub">Waiting for marks</span>'}</td></tr>`; }).join('')}</tbody></table></div></div>
  <div class="card"><div class="hd"><h2>Average by class</h2><small>Mid-term · entered so far</small></div>${bars(rows.slice(0, 6).map((r, i) => [r[0].replace('Primary ', 'P.') + ' ' + r[1], 60 + (i * 5) % 14]))}<p class="sub" style="margin:0">3 classes have no Mid-term marks yet.</p></div></div>`;
};
/* ---------- Attendance overview ---------- */
const vbars = (pts, lo = 80) => { const w = 360, h = 170, bw = (w - 40) / pts.length, y = v => 14 + (100 - v) / (100 - lo) * (h - 50);
  return `<svg class="ch" viewBox="0 0 ${w} ${h}" role="img" aria-label="${pts.map(p => p[0] + ' ' + p[1] + '%').join(', ')}">${[80, 90, 100].map(v => `<line x1="30" x2="${w - 6}" y1="${y(v)}" y2="${y(v)}" stroke="#E2E8F0"/><text x="26" y="${y(v) + 4}" text-anchor="end" font-size="11" fill="#475569">${v}%</text>`).join('')}${pts.map((p, i) => { const x = 34 + i * bw; return `<rect x="${x + 6}" y="${y(p[1])}" width="${bw - 12}" height="${h - 36 - y(p[1])}" rx="4" fill="${p[2] || '#15803D'}"/><text x="${x + bw / 2}" y="${y(p[1]) - 6}" text-anchor="middle" font-size="11" font-weight="700" fill="#0F172A">${p[1]}%</text><text x="${x + bw / 2}" y="${h - 18}" text-anchor="middle" font-size="11" fill="#475569">${p[0]}</text>`; }).join('')}</svg>`; };
window.scrAttendance = () => {
  const head = `<div class="ph"><div><h1>Attendance</h1><p>Today · Thursday 8 October 2026</p></div><div class="row-acts"><label class="ay">Period <select class="sel" aria-label="Period"><option selected>This week</option><option>This term</option><option>Last 8 weeks</option></select></label><a class="btn" href="#">${ic('download')}Export</a></div></div>`;
  if (ST.state === 'empty') return head + `<div class="empty"><b>No attendance taken yet this term</b><p>Class teachers take the register each morning. Patterns by class and by day appear after the first week.</p><a class="btn pri" href="#">${ic('bell')}Remind class teachers</a></div>`;
  const REG = STREAMS.map((r, i) => ({ c: r[0] + ' · ' + r[1], t: tt(r[2]), n: r[3], ok: i !== 3 && i !== 5, at: ['07:52', '08:05', '08:20', '', '08:12', '', '08:12', '08:31', '07:58'][i] })).concat([{ c: 'Nursery · Sunflower', t: tt('t7'), n: 22, ok: true, at: '08:02' }, { c: 'Reception · Sunflower', t: tt('t8'), n: 24, ok: true, at: '08:09' }]);
  REG.sort((a, b) => a.ok - b.ok);
  return head + `<div class="kpis k4">${kpi('user-round-check', 'Present today', '93.1%', '231 of 248 · 17 absent', '', 93.1)}<div class="kpi"><span class="l">${ic('clipboard-check', 'ic ic-sm')}Registers taken today</span><span class="v">9 of 11</span><span class="meter" role="img" aria-label="9 of 11"><i style="width:82%"></i></span><span class="s warn">2 not taken yet</span></div>${kpi('calendar-check', 'This week', '93.4%', '▲ 1.2 pts on last week', 'up')}${kpi('calendar-range', 'This term', '92.6%', 'Since 7 September')}</div>
  <div class="grid3"><div class="card"><div class="hd"><h2>Who has taken today</h2><small>Not taken first</small></div><ul class="reg">${REG.map(r => `<li><span style="min-width:0"><b class="trunc">${r.c}</b><span class="tch">${av(r.t, 24)}<span class="trunc sub" style="display:inline">${r.t.fn} ${r.t.ln}</span></span></span>${r.ok ? `<span class="badge b-ok">Taken ${r.at}</span>` : `<span class="row-acts"><span class="badge b-warn">Not yet</span><a class="btn" href="#">${ic('bell')}Remind</a></span>`}</li>`).join('')}</ul></div>
  <div class="card"><div class="hd"><h2>By day of the week</h2><small>This term</small></div>${vbars([['Mon', 94], ['Tue', 95], ['Wed', 94], ['Thu', 93], ['Fri', 89, '#B45309']])}<p class="note">${ic('info', 'ic ic-sm')}Fridays average 5 points below the rest of the week.</p></div></div>
  <div class="grid2"><div class="card"><div class="hd"><h2>By class</h2><small>This week</small></div>${bars(STREAMS.map((r, i) => [r[0].replace('Primary ', 'P.') + ' ' + r[1], [96, 95, 93, 92, 92, 91, 95, 93, 90][i]]))}</div>
  <div class="card"><div class="hd"><h2>Trend</h2><small>Last 8 weeks · whole school</small></div>${line([['W1', 91], ['W2', 92], ['W3', 90], ['W4', 93], ['W5', 94], ['W6', 92], ['W7', 92.2], ['W8', 93.4]])}</div></div>`;
};
/* ---------- Exams, subject first ---------- */
window.scrExams = () => {
  const ex = SUB.filter(s => !s.nur);
  const tot = ex.reduce((a, s) => a + rowsOf(s).length, 0), done = ex.reduce((a, s) => a + s.ent, 0);
  const open = ST.open || 'mth';
  const head = `<div class="ph"><div><h1>Exams and marks</h1><p>${SCHOOL.term}, ${SCHOOL.year} · by subject</p></div><div class="row-acts"><label class="ay">Term <select class="sel" aria-label="Term"><option selected>Term 3, 2026</option><option>Term 2, 2026</option></select></label><a class="btn pri" href="#">${ic('plus')}Add exam</a></div></div>
  <div class="chips" role="group" aria-label="Exam"><button class="chip" type="button" aria-pressed="false">Beginning of term <span class="n">· Complete</span></button><button class="chip" type="button" aria-pressed="true">Mid-term <span class="n">· In progress</span></button><button class="chip" type="button" aria-pressed="false">End of term <span class="n">· From 24 Nov</span></button></div>`;
  if (ST.state === 'empty') return head.replace(/<div class="chips"[\s\S]*$/, '') + `<div class="empty"><b>No exams this term</b><p>Add an exam, such as a mid-term or end-of-term exam, then choose its subjects and classes. Teachers enter marks per subject.</p><a class="btn pri" href="#">${ic('plus')}Add exam</a></div>`;
  return head + `<div class="card exsum"><div style="min-width:0;flex:1 1 280px"><h2>Mid-term exams · 5–9 October</h2><p style="margin:4px 0 8px">Marks entered for <b>${done} of ${tot}</b> subject classes</p><span class="prog" style="height:8px" role="progressbar" aria-valuemin="0" aria-valuemax="${tot}" aria-valuenow="${done}" aria-label="Marks entered"><i style="width:${done / tot * 100}%"></i></span></div>
   <div class="exrc"><span><b>Report cards</b><span class="sub">4 of 11 classes have every mark</span></span><span class="row-acts"><a class="btn" href="#">${ic('bell')}Remind teachers</a><a class="btn pri" href="#">${ic('file-text')}Generate for 4 classes</a></span></div></div>
  <div class="lt"><label class="search"><span class="sr">Search subjects</span>${ic('search')}<input type="search" placeholder="Search subjects"></label><div class="chips" role="group" aria-label="Status"><button class="chip" type="button" aria-pressed="true">All <span class="n">6</span></button><button class="chip" type="button" aria-pressed="false">Not started <span class="n">1</span></button><button class="chip" type="button" aria-pressed="false">In progress <span class="n">3</span></button><button class="chip" type="button" aria-pressed="false">Complete <span class="n">2</span></button></div></div>
  <ul class="xl">${ex.map(s => { const rows = rowsOf(s), n = rows.length, o = open === s.id; return `<li class="${o ? 'open' : ''}"><div class="xh"><button class="btn icon ghost" type="button" data-act="tog" data-id="${s.id}" aria-expanded="${o}" aria-controls="x-${s.id}" aria-label="${o ? 'Hide' : 'Show'} classes for ${s.n}">${ic(o ? 'chevron-down' : 'chevron-right')}</button>
   <span class="xn"><a href="#" data-go="subject"><b>${s.n}</b></a><span class="tch">${avs(s.tch)}<span class="sub" style="display:inline">${n} classes</span></span></span>${prog(s.ent, n)}<span class="hm">${stat(s.ent, n)}</span><span class="hm xa">${s.avg && s.ent ? `Avg <b>${s.avg}%</b>` : '<span class="sub">–</span>'}</span>${menu('x' + s.id, ['Download all marksheets', 'Import from spreadsheet', 'Remind teachers'])}</div>
   ${o ? `<ul class="xc" id="x-${s.id}">${rows.map((r, i) => { const a = i < s.ent ? r[3] : i === s.ent ? Math.round(r[3] / 2) : 0; const t = tt(s.tch[i % s.tch.length]); return `<li><span style="min-width:0"><b class="trunc">${r[0]} · ${r[1]}</b><span class="tch">${av(t, 24)}<span class="sub trunc" style="display:inline">${t.fn} ${t.ln}</span></span></span>${a === r[3] ? `<span class="badge b-ok">Entered ${a}/${r[3]}</span>` : a ? `<span class="badge b-warn">${a} of ${r[3]}</span>` : '<span class="badge b-off">Not started</span>'}<span class="row-acts"><a class="btn${a === r[3] ? '' : ' pri'}" href="#">${a === r[3] ? 'View' : 'Enter marks'}</a>${menu('c' + s.id + i, ['Import from spreadsheet', 'Download marksheet', 'Remind teacher'])}</span></li>`; }).join('')}</ul>` : ''}</li>`; }).join('')}</ul>
  <p class="sub" style="margin:0">Language, Numbers and Reading (Nursery and Reception) have no Mid-term exam.</p>`;
};
})();
